### ISSUE TITLE
这个是类似于阿里PAI的东西吗？

### ISSUE THREAD

**Issue by yayaQAQ** [jiaxincao/model-factory#1]

**Comment by jiaxincao** [comment]
PAI和model-factory解决的问题类似，都解决了model training resource orchestration & management的问题，不过方法不太一样。

* 我感觉阿里PAI更像是Databrick MLFlow, Amazon SageMaker一样的东西。看起来PAI是一个notebook based的framework。
* model-factory更像是一个给developer使用的framework，基本上是完全是code based的，跟你使用gcc, python之类的感觉差不多，写好model training pipeline了，然后就可以submit job执行。具体使用方法可以参考，https://github.com/jiaxincao/model-factory/blob/master/docs/development_guide.md 。model-factory更像是facebook fblearner, google kubeflow，最大的区别是model-factory并不用DAG执行模型，这样你就可以在model-factory上做distributed training.

另外阿里PAI好像做了很多training framework integration的工作，看起来好像是只support tensorflow（不过我不太确定）。model-factory没做任何这方面的工作，所以model-factory里面你想用任何training framework都可以，tf, torch，等等。

**Comment by yayaQAQ** [comment]
> PAI和model-factory解决的问题类似，都解决了model training resource orchestration & management的问题，不过方法不太一样。
> 
> * 我感觉阿里PAI更像是Databrick MLFlow, Amazon SageMaker一样的东西。看起来PAI是一个notebook based的framework。
> * model-factory更像是一个给developer使用的framework，基本上是完全是code based的，跟你使用gcc, python之类的感觉差不多，写好model training pipeline了，然后就可以submit job执行。具体使用方法可以参考，https://github.com/jiaxincao/model-factory/blob/master/docs/development_guide.md 。model-factory更像是facebook fblearner, google kubeflow，最大的区别是model-factory并不用DAG执行模型，这样你就可以在model-factory上做distributed training.
> 
> 另外阿里PAI好像做了很多training framework integration的工作，看起来好像是只support tensorflow（不过我不太确定）。model-factory没做任何这方面的工作，所以model-factory里面你想用任何training framework都可以，tf, torch，等等。

感谢你的回复，希望这个项目可以继续做下去
